### ISSUE TITLE
Are the Attention and Feedforward weights of the Encoder frozen during the Prompt-tuning phase?

### ISSUE THREAD

**Issue by SliverLining340** [tsinghua-fib-lab/UniST#16]
I've run the prompt_tuning script and observed the weight values. I noticed that the Attention and Feedforward weights of the Encoder are changing rather than being frozen as described in the paper. I just want to confirm if these weights are supposed to be frozen or if I might have made a mistake.

**Comment by YuanYuan98** [comment]
Both options—frozen or not frozen weights—are valid approaches. In my experiments, the effectiveness of freezing the weights has varied depending on the dataset. For some datasets, freezing the weights yielded better results, while for others, not freezing them was more beneficial. If you have a large amount of training data, I would suggest that not freezing the weights might lead to improved performance.

**Comment by SliverLining340** [comment]
Thanks
