### ISSUE TITLE
Question about four mask strategies.

### ISSUE THREAD

**Issue by packer-c** [tsinghua-fib-lab/UniST#2]
Hi, thank you for your nice work and for sharing the code.

I would like to know about the mask strategies. Are these four strategies working together or individually (['random','causal','frame','tube'])? I saw that in your code "main.py", you set mask_strategy = 'random', which seems to use only one random strategy but not use others. Which one is the best mask strategy effect?

Look forward to your reply. Thanks in advance!

**Comment by YuanYuan98** [comment]
Thanks for your interest!

To clarify, the parameter mask_strategy determines the strategy used for masking during training. If `mask_strategy_random` is set to `none`, then mask_strategy dictates which specific strategy ('random', 'causal', 'frame', 'tube') is applied uniformly across all batches. On the other hand, if `mask_strategy_random` is set to `batch`, the masking strategy is randomly selected from the four options for each training batch.

**Comment by packer-c** [comment]
Clear! Thanks for your kindly reply.
