### ISSUE TITLE
Pretrained model weights

### ISSUE THREAD

**Issue by szz34** [tsinghua-fib-lab/UniST#25]
Hello, thank you for your contribution to the code.

* I would like to ask if the **model_Emb.pkl** and **model_SinCos.pkl** stored in _./model_weights_ are complete pre-trained model weights? Do they refer to the **model_best.pkl** mentioned in the README?

* Also, I would like to know what is the minimum hardware resources required to train this model from scratch using the entire dataset? What is the approximate training time required?

**Comment by YuanYuan98** [comment]
The **model_Emb.pkl** and **model_SinCos.pkl** represent the best-performing model weights (model_best.pkl).

The hardware requirements depend on the **batch size** and **patch_size** you choose. Reducing the batch size or increasing the patch_size allows training on lower-resource hardware, such as a single GPU with 8–12 GB of memory, though it will increase the training time. Adjusting the batch size can help you adapt to your available computational resources.

**Comment by Gs0098** [comment]
> 您好，感谢您对代码的贡献。
> 
> * 我想问一下存储在 _./model_weights_ 中的 **model_Emb.pkl** 和 **model_SinCos.pkl** 是否是完整的预训练模型权重？它们是否引用了 README 中提到的 **model_best.pkl**？
> * 此外，我想知道使用整个数据集从头开始训练此模型所需的最低硬件资源是多少？大约需要多少培训时间？
请问 这2个文件是同时加载吗 还是只加载一个
