### ISSUE TITLE
Temporal Duration and Temporal interval

### ISSUE THREAD

**Issue by kasanatte** [tsinghua-fib-lab/UniST#6]
Hi, thank you for your nice work and for sharing the code.

I want to know how to deal with the data of different time intervals and different dates. the timestamps in your data only include the day of the week and time of day. But the data has different dates and different time intervals.

The range of timestamps for TrafficNJ and BikeNYC-1 in dataloader seems to be [0-6,0-47]?
When his_len=6, TrafficCS predicts 6 frames(5 minute intervals) and TDrive predicts 6 frames(1 hour intervals)？
And why doesn't the timestamp include the year, month, and day?

Look forward to your reply. Thanks in advance!

**Comment by YuanYuan98** [comment]
Your understanding is correct: the prediction frames indeed vary across different datasets.

In our approach, we focus solely on the time of day and the day of the week. Given that our dataset spans only a few months, we intentionally omit the year, month, and exact date. This simplification allows us to better capture daily and weekly patterns, which are often more significant for the predictions.
